version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./backend/public/uploads:/app/public/uploads
      

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
